In [1]:
import numpy as np
import pandas as pd

import cfbd

import requests
import json
import os
import sys
from datetime import datetime as dt

In [2]:
df = pd.read_csv("/Users/taylorlast/PersonalProjects/cfb-predictions/data/training_sets/af9452345d7311efb6293e22fb810d5d_20240818_110812.csv")

In [3]:
# df = df[
#     ~((df["season"] == 2015) & (df["week"] == 1))
#     & (df["season"] != 2024)
# ]

# df = df[
#     df["season"].isin([2021,2022,2023])
# ]

In [4]:
df[df["season"] == 2023]

,id,season,week,home_team,away_team,home_points,away_points,home_division,away_division,home_pregame_elo,...,rushing_plays.ppa_defense_away,rushing_plays.total_ppa_defense_away,rushing_plays.success_rate_defense_away,rushing_plays.explosiveness_defense_away,passing_plays.ppa_defense_away,passing_plays.total_ppa_defense_away,passing_plays.success_rate_defense_away,passing_plays.explosiveness_defense_away,bovada_spread,diff
5620,401525434,2023,1,Notre Dame,Navy,42.0,3.0,fbs,fbs,1733.0,...,0.058624,0.770451,0.363590,1.128783,0.409966,12.482634,0.406967,1.934818,-20.5,-18.5
5621,401520145,2023,1,Jacksonville State,UTEP,17.0,14.0,fbs,fbs,1500.0,...,-0.039852,0.075876,0.426362,0.793799,0.515430,14.887758,0.444822,2.147052,1.0,-4.0
5622,401532392,2023,1,San Diego State,Ohio,20.0,13.0,fbs,fbs,1488.0,...,-0.003582,0.435792,0.348725,0.884063,0.313226,9.543562,0.425813,1.631239,-2.5,-4.5
5623,401525450,2023,1,New Mexico State,UMass,30.0,41.0,fbs,fbs,1322.0,...,0.226588,9.600387,0.427342,1.251787,0.318395,6.281362,0.354379,1.985439,-7.5,18.5
5624,401520147,2023,1,Vanderbilt,Hawai'i,35.0,28.0,fbs,fbs,1322.0,...,0.143576,5.689712,0.453611,0.930302,0.428651,12.926086,0.426560,1.808547,-18.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6365,401539477,2023,14,Tulane,SMU,14.0,26.0,fbs,fbs,1657.0,...,0.063199,1.189724,0.363059,1.066649,-0.151721,-3.125068,0.299870,1.445448,-2.5,14.5
6366,401539484,2023,14,Troy,Appalachian State,49.0,23.0,fbs,fbs,1696.0,...,0.132951,4.044605,0.398765,1.033381,0.341663,10.754626,0.432375,1.600365,-5.5,-20.5
6367,401539478,2023,14,Florida State,Louisville,16.0,6.0,fbs,fbs,1943.0,...,0.008285,0.596022,0.361544,0.992971,0.156373,5.111116,0.352502,1.759923,1.5,-11.5
6368,401539480,2023,14,Iowa,Michigan,0.0,26.0,fbs,fbs,1675.0,...,0.001635,0.311823,0.383760,0.836315,0.004788,1.530350,0.330510,1.545799,21.0,5.0
6369,401520445,2023,15,Army,Navy,17.0,11.0,fbs,fbs,1379.0,...,-0.042686,-1.040418,0.307878,0.846794,0.427615,7.167848,0.438428,1.884237,-2.5,-3.5

In [5]:
df

,id,season,week,home_team,away_team,home_points,away_points,home_division,away_division,home_pregame_elo,...,rushing_plays.ppa_defense_away,rushing_plays.total_ppa_defense_away,rushing_plays.success_rate_defense_away,rushing_plays.explosiveness_defense_away,passing_plays.ppa_defense_away,passing_plays.total_ppa_defense_away,passing_plays.success_rate_defense_away,passing_plays.explosiveness_defense_away,bovada_spread,diff
0,400603840,2015,1,South Carolina,North Carolina,17.0,13.0,fbs,fbs,1646.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,400763593,2015,1,UCF,Florida International,14.0,15.0,fbs,fbs,1626.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,400763399,2015,1,Central Michigan,Oklahoma State,13.0,24.0,fbs,fbs,1417.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,400603839,2015,1,Vanderbilt,Western Kentucky,12.0,14.0,fbs,fbs,1365.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,400756883,2015,1,Utah,Michigan,24.0,17.0,fbs,fbs,1603.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7109,401643847,2024,14,Arkansas State,Old Dominion,NaN,NaN,fbs,fbs,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7110,401643773,2024,14,Washington State,Wyoming,NaN,NaN,fbs,fbs,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7111,401643772,2024,14,UNLV,Nevada,NaN,NaN,fbs,fbs,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7112,401643771,2024,14,Hawai'i,New Mexico,NaN,NaN,fbs,fbs,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7113,401645383,2024,16,Army,Navy,NaN,NaN,fbs,fbs,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Local Imports
from resources.helper import load_configs, authenticate_api, get_latest_version_number
from preprocessing.data_gathering import get_game_stats, get_games, get_betting_info
from preprocessing.preprocessing import DataProcessor

# Load configs
api_configs_path = "/Users/taylorlast/PersonalProjects/cfb-predictions/configs/api_configs.yml"
api_configs = load_configs(config_path=api_configs_path)

# Auth API
api_configuration = authenticate_api(api_key=api_configs["API_KEY"])

In [7]:
stats = get_game_stats(configuration=api_configuration, year=2023)

In [8]:
stats

,id,season,week,team,opponent,plays_offense,drives_offense,ppa_offense,total_ppa_offense,success_rate_offense,...,passing_downs.success_rate_defense,passing_downs.explosiveness_defense,rushing_plays.ppa_defense,rushing_plays.total_ppa_defense,rushing_plays.success_rate_defense,rushing_plays.explosiveness_defense,passing_plays.ppa_defense,passing_plays.total_ppa_defense,passing_plays.success_rate_defense,passing_plays.explosiveness_defense
0,401520145,2023,1,Jacksonville State,UTEP,64,11,0.030189,1.932072,0.343750,...,0.222222,1.244899,0.072080,2.883202,0.475000,0.621208,0.232453,6.508697,0.428571,1.455518
1,401520145,2023,1,UTEP,Jacksonville State,70,11,0.060931,4.265143,0.442857,...,0.235294,1.937469,0.068540,2.947238,0.372093,0.999348,-0.048341,-1.015166,0.285714,1.347663
2,401520146,2023,1,Florida International,Louisiana Tech,43,12,0.034831,1.497746,0.325581,...,0.233333,2.475236,-0.130298,-4.821029,0.297297,1.095379,0.468497,19.676859,0.500000,1.546979
3,401520146,2023,1,Louisiana Tech,Florida International,80,13,0.141654,11.332343,0.400000,...,0.133333,0.627508,0.339656,9.510381,0.500000,1.144627,-0.582676,-8.157464,0.000000,NaN
4,401520147,2023,1,Hawai'i,Vanderbilt,59,11,0.240675,14.199816,0.440678,...,0.291667,2.867208,-0.314656,-7.237081,0.304348,0.906540,0.405533,13.382574,0.393939,1.974577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,401618100,2023,1,Harding,Colorado Mines,47,6,0.597435,28.079448,0.574468,...,0.454545,1.942483,-0.275262,-3.853666,0.357143,1.481209,0.292129,7.303228,0.480000,1.592877
2962,401618101,2023,1,North Central,SUNY Cortland,58,9,0.563876,32.704836,0.551724,...,0.590909,2.369344,0.124878,3.996108,0.500000,1.146428,0.775393,27.138764,0.571429,1.694819
2963,401618101,2023,1,SUNY Cortland,North Central,67,9,0.464700,31.134871,0.537313,...,0.555556,2.363440,0.805902,30.624271,0.631579,1.410132,0.104028,2.080565,0.400000,1.998843
2964,401618179,2023,1,Albany,South Dakota State,60,11,-0.069442,-4.166521,0.466667,...,0.666667,3.204061,0.386613,11.985008,0.677419,0.789684,1.296846,25.936928,0.800000,1.847366
2965,401618179,2023,1,South Dakota State,Albany,51,9,0.743567,37.921935,0.725490,...,0.058824,1.508687,-0.249850,-3.497895,0.214286,0.878102,-0.014535,-0.668626,0.543478,0.746994

In [9]:
data_processor = DataProcessor()
stats_df = data_processor.get_simple_rolling_stats(stats)

In [10]:
stats[stats["team"] == "Georgia"][["id", "week", "team", "opponent", "plays_offense", "drives_offense"]].sort_values("id")

             id  week     team        opponent  plays_offense  drives_offense
18    401520154     1  Georgia       UT Martin             70              12
91    401520191     2  Georgia      Ball State             61              12
158   401520225     3  Georgia  South Carolina             78              11
208   401520252     4  Georgia             UAB             76              12
265   401520280     5  Georgia          Auburn             62              10
304   401520300     6  Georgia        Kentucky             73              11
358   401520327     7  Georgia      Vanderbilt             77              10
409   401520352     9  Georgia         Florida             66              12
432   401520364    10  Georgia        Missouri             65              10
468   401520382    11  Georgia        Ole Miss             60              11
542   401520419    12  Georgia       Tennessee             70              10
564   401520430    13  Georgia    Georgia Tech             58               8
1729  401539483    14  Georgia         Alabama             59              11
2897  401551773     1  Georgia   Florida State             76              12

In [18]:
stats_df[stats_df["team"] == "Georgia"].sort_values("id")[["team", "id", "plays_offense", "drives_offense"]]

        team         id  plays_offense  drives_offense
805  Georgia  401520154            NaN             NaN
806  Georgia  401520191      70.000000       12.000000
807  Georgia  401520225      65.500000       12.000000
808  Georgia  401520252      69.666667       11.666667
809  Georgia  401520280      71.250000       11.750000
810  Georgia  401520300      69.400000       11.400000
811  Georgia  401520327      70.000000       11.333333
812  Georgia  401520352      71.000000       11.142857
813  Georgia  401520364      70.428571       11.142857
814  Georgia  401520382      71.000000       10.857143
815  Georgia  401520419      68.428571       10.857143
816  Georgia  401520430      67.571429       10.571429
817  Georgia  401539483      67.000000       10.285714
818  Georgia  401551773      65.000000       10.285714

In [19]:
# df[df["team"] == "Georgia"]
df[((df["home_team"] == "Georgia") | (df["away_team"] == "Georgia")) & (df["season"] == 2023)][["id", "home_team", "away_team", "plays_offense_home", "drives_offense_away"]].sort_values("id")

,id,home_team,away_team,plays_offense_home,drives_offense_away
5678,401520191,Georgia,Ball State,67.571429,13.142857
5734,401520225,Georgia,South Carolina,67.714286,12.571429
5825,401520252,Georgia,UAB,68.857143,10.857143
5869,401520280,Auburn,Georgia,67.142857,12.000000
5927,401520300,Georgia,Kentucky,70.714286,11.285714
5951,401520327,Vanderbilt,Georgia,62.000000,11.428571
6079,401520352,Florida,Georgia,66.714286,11.142857
6132,401520364,Georgia,Missouri,70.428571,12.142857
6214,401520382,Georgia,Ole Miss,71.000000,12.000000
6271,401520419,Tennessee,Georgia,68.000000,10.857143
6351,401520430,Georgia Tech,Georgia,63.285714,10.571429
6364,401539483,Alabama,Georgia,62.857143,10.285714

In [15]:
stats

,id,season,week,team,opponent,plays_offense,drives_offense,ppa_offense,total_ppa_offense,success_rate_offense,...,passing_downs.success_rate_defense,passing_downs.explosiveness_defense,rushing_plays.ppa_defense,rushing_plays.total_ppa_defense,rushing_plays.success_rate_defense,rushing_plays.explosiveness_defense,passing_plays.ppa_defense,passing_plays.total_ppa_defense,passing_plays.success_rate_defense,passing_plays.explosiveness_defense
0,401520145,2023,1,Jacksonville State,UTEP,64,11,0.030189,1.932072,0.343750,...,0.222222,1.244899,0.072080,2.883202,0.475000,0.621208,0.232453,6.508697,0.428571,1.455518
1,401520145,2023,1,UTEP,Jacksonville State,70,11,0.060931,4.265143,0.442857,...,0.235294,1.937469,0.068540,2.947238,0.372093,0.999348,-0.048341,-1.015166,0.285714,1.347663
2,401520146,2023,1,Florida International,Louisiana Tech,43,12,0.034831,1.497746,0.325581,...,0.233333,2.475236,-0.130298,-4.821029,0.297297,1.095379,0.468497,19.676859,0.500000,1.546979
3,401520146,2023,1,Louisiana Tech,Florida International,80,13,0.141654,11.332343,0.400000,...,0.133333,0.627508,0.339656,9.510381,0.500000,1.144627,-0.582676,-8.157464,0.000000,NaN
4,401520147,2023,1,Hawai'i,Vanderbilt,59,11,0.240675,14.199816,0.440678,...,0.291667,2.867208,-0.314656,-7.237081,0.304348,0.906540,0.405533,13.382574,0.393939,1.974577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,401618100,2023,1,Harding,Colorado Mines,47,6,0.597435,28.079448,0.574468,...,0.454545,1.942483,-0.275262,-3.853666,0.357143,1.481209,0.292129,7.303228,0.480000,1.592877
2962,401618101,2023,1,North Central,SUNY Cortland,58,9,0.563876,32.704836,0.551724,...,0.590909,2.369344,0.124878,3.996108,0.500000,1.146428,0.775393,27.138764,0.571429,1.694819
2963,401618101,2023,1,SUNY Cortland,North Central,67,9,0.464700,31.134871,0.537313,...,0.555556,2.363440,0.805902,30.624271,0.631579,1.410132,0.104028,2.080565,0.400000,1.998843
2964,401618179,2023,1,Albany,South Dakota State,60,11,-0.069442,-4.166521,0.466667,...,0.666667,3.204061,0.386613,11.985008,0.677419,0.789684,1.296846,25.936928,0.800000,1.847366
2965,401618179,2023,1,South Dakota State,Albany,51,9,0.743567,37.921935,0.725490,...,0.058824,1.508687,-0.249850,-3.497895,0.214286,0.878102,-0.014535,-0.668626,0.543478,0.746994

In [13]:
games = get_games(configuration=api_configuration, year=2024, only_fbs=True, week=1)

In [38]:
stats_df_rolling = (
        stats
        .sort_values(by=["season", "week"])
        .drop(["opponent", "week", "season"],axis=1)
        .set_index("id")
        .groupby("team")
        .rolling(7, min_periods=1)
        .mean()
        .groupby("team")
        .shift(1)
        .reset_index()
)

In [39]:
stats_df_rolling

,team,id,plays_offense,drives_offense,ppa_offense,total_ppa_offense,success_rate_offense,explosiveness_offense,power_success_offense,stuff_rate_offense,...,passing_downs.success_rate_defense,passing_downs.explosiveness_defense,rushing_plays.ppa_defense,rushing_plays.total_ppa_defense,rushing_plays.success_rate_defense,rushing_plays.explosiveness_defense,passing_plays.ppa_defense,passing_plays.total_ppa_defense,passing_plays.success_rate_defense,passing_plays.explosiveness_defense
0,Abilene Christian,401540278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abilene Christian,401541630,69.000000,10.000000,0.400349,27.624106,0.637681,0.993069,0.833333,0.097561,...,0.240000,2.326414,0.097555,2.341309,0.291667,1.257389,-0.085112,-2.808709,0.242424,1.653654
2,Abilene Christian,401531436,60.500000,10.000000,0.139008,10.631391,0.482302,1.069417,0.416667,0.220655,...,0.338750,2.108407,0.180914,3.813384,0.345833,1.304060,0.178296,6.104624,0.327094,1.882649
3,Abilene Christian,401541631,63.333333,11.000000,0.173039,12.632889,0.471293,1.128048,0.515873,0.191548,...,0.356268,2.284748,0.216498,6.377800,0.397222,1.262872,0.267668,9.426683,0.366211,1.826010
4,Abilene Christian,401540209,65.750000,11.750000,0.184912,13.499393,0.469908,1.127810,0.636905,0.174911,...,0.350534,2.267858,0.213599,6.422577,0.422917,1.174495,0.278426,10.332361,0.381801,1.797991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,Youngstown State,401540304,65.285714,11.857143,0.335844,22.273081,0.465468,1.274927,0.738095,0.140126,...,0.328886,2.013991,0.130800,2.924419,0.365991,1.186810,0.477451,16.223090,0.463870,1.634706
2962,Youngstown State,401540453,67.857143,12.142857,0.348868,23.435415,0.472486,1.279006,0.809524,0.137493,...,0.292551,2.452827,0.093202,1.924245,0.356158,1.239253,0.367606,12.462503,0.428156,1.608083
2963,Youngstown State,401540368,65.714286,11.857143,0.234313,15.990470,0.433362,1.190680,0.738095,0.144295,...,0.296691,2.265537,0.091444,2.256211,0.375124,1.156906,0.390274,13.210527,0.454130,1.521750
2964,Youngstown State,401614600,65.714286,11.571429,0.219210,14.963438,0.429161,1.175425,0.753968,0.139056,...,0.283766,2.251896,0.102189,2.507133,0.406552,1.016789,0.316253,11.035384,0.416992,1.567779
2965,Youngstown State,401615939,66.714286,11.285714,0.257729,17.845464,0.451608,1.168824,0.760771,0.127717,...,0.272689,2.199448,0.087629,2.278881,0.394998,1.040900,0.327706,11.688789,0.411899,1.673671

In [5]:
lines = get_betting_info(configuration=api_configuration, year=2024, week=1)

In [6]:
lines

,id,season,week,season_type,start_date,home_team,home_conference,home_score,away_team,away_conference,away_score,lines,bovada_spread
0,401628332,2024,1,regular,2024-08-31T23:30:00.000Z,Texas A&M,SEC,None,Notre Dame,FBS Independents,None,"[{'provider': 'Bovada', 'spread': -2.5, 'forma...",-2.5
1,401634300,2024,1,regular,2024-08-31T02:30:00.000Z,Stanford,ACC,None,TCU,Big 12,None,"[{'provider': 'Bovada', 'spread': 8.0, 'format...",8.0
2,401628328,2024,1,regular,2024-08-30T23:00:00.000Z,Oklahoma,SEC,None,Temple,American Athletic,None,"[{'provider': 'Bovada', 'spread': -42.5, 'form...",-42.5
3,401628319,2024,1,regular,2024-08-31T23:00:00.000Z,Alabama,SEC,None,Western Kentucky,Conference USA,None,"[{'provider': 'Bovada', 'spread': -31.0, 'form...",-31.0
4,401628449,2024,1,regular,2024-08-31T19:30:00.000Z,Indiana,Big Ten,None,Florida International,Conference USA,None,"[{'provider': 'Bovada', 'spread': -21.0, 'form...",-21.0
5,401628454,2024,1,regular,2024-08-31T19:30:00.000Z,Nebraska,Big Ten,None,UTEP,Conference USA,None,"[{'provider': 'Bovada', 'spread': -27.5, 'form...",-27.5
6,401643774,2024,1,regular,2024-09-01T00:00:00.000Z,Charlotte,American Athletic,None,James Madison,Sun Belt,None,"[{'provider': 'Bovada', 'spread': 7.5, 'format...",7.5
7,401628329,2024,1,regular,2024-08-31T20:15:00.000Z,South Carolina,SEC,None,Old Dominion,Sun Belt,None,"[{'provider': 'Bovada', 'spread': -20.0, 'form...",-20.0
8,401640998,2024,1,regular,2024-08-30T00:00:00.000Z,Jacksonville State,Conference USA,None,Coastal Carolina,Sun Belt,None,"[{'provider': 'Bovada', 'spread': -3.5, 'forma...",-3.5
9,401634302,2024,1,regular,2024-09-01T00:00:00.000Z,Georgia Tech,ACC,None,Georgia State,Sun Belt,None,"[{'provider': 'Bovada', 'spread': -20.5, 'form...",-20.5
10,401628324,2024,1,regular,2024-08-31T23:45:00.000Z,Kentucky,SEC,None,Southern Mississippi,Sun Belt,None,"[{'provider': 'Bovada', 'spread': -26.0, 'form...",-26.0
11,401628451,2024,1,regular,2024-08-31T16:00:00.000Z,Maryland,Big Ten,None,Connecticut,FBS Independents,None,"[{'provider': 'Bovada', 'spread': -20.5, 'form...",-20.5
12,401634206,2024,1,regular,2024-08-30T00:00:00.000Z,Colorado,Big 12,None,North Dakota State,MVFC,None,"[{'provider': 'Bovada', 'spread': -8.5, 'forma...",-8.5
13,401634212,2024,1,regular,2024-08-31T18:00:00.000Z,Oklahoma State,Big 12,None,South Dakota State,MVFC,None,"[{'provider': 'Bovada', 'spread': -9.5, 'forma...",-9.5
14,401628453,2024,1,regular,2024-08-30T23:00:00.000Z,Michigan State,Big Ten,None,Florida Atlantic,American Athletic,None,"[{'provider': 'Bovada', 'spread': -11.5, 'form...",-11.5
15,401643775,2024,1,regular,2024-08-31T21:00:00.000Z,South Alabama,Sun Belt,None,North Texas,American Athletic,None,"[{'provider': 'Bovada', 'spread': -6.0, 'forma...",-6.0
16,401641039,2024,1,regular,2024-08-31T23:00:00.000Z,Rice,American Athletic,None,Sam Houston State,Conference USA,None,"[{'provider': 'Bovada', 'spread': -10.5, 'form...",-10.5
17,401635525,2024,1,regular,2024-08-24T16:00:00.000Z,Georgia Tech,ACC,None,Florida State,ACC,None,"[{'provider': 'Bovada', 'spread': 11.0, 'forma...",11.0
18,401634306,2024,1,regular,2024-09-02T23:30:00.000Z,Florida State,ACC,None,Boston College,ACC,None,"[{'provider': 'Bovada', 'spread': -21.5, 'form...",-21.5
19,401628448,2024,1,regular,2024-08-30T00:00:00.000Z,Minnesota,Big Ten,None,North Carolina,ACC,None,"[{'provider': 'Bovada', 'spread': -2.5, 'forma...",-2.5
20,401628323,2024,1,regular,2024-08-31T16:00:00.000Z,Georgia,SEC,None,Clemson,ACC,None,"[{'provider': 'Bovada', 'spread': -14.0, 'form...",-14.0
21,401628333,2024,1,regular,2024-08-31T16:00:00.000Z,Vanderbilt,SEC,None,Virginia Tech,ACC,None,"[{'provider': 'Bovada', 'spread': 13.5, 'forma...",13.5
22,401628322,2024,1,regular,2024-08-31T19:30:00.000Z,Florida,SEC,None,Miami,ACC,None,"[{'provider': 'Bovada', 'spread': 2.0, 'format...",2.0
23,401643696,2024,1,regular,2024-08-25T00:00:00.000Z,Nevada,Mountain West,None,SMU,ACC,None,"[{'provider': 'Bovada', 'spread': 27.5, 'forma...",27.5
24,401628459,2024,1,regular,2024-08-31T23:30:00.000Z,Hawai'i,Mountain West,None,UCLA,Big Ten,None,"[{'provider': 'Bovada', 'spread': 13.5, 'forma...",13.5
25,401628334,2024,1,regular,2024-09-01T23:30:00.000Z,LSU,SEC,None,USC,Big Ten,None,"[{'provider': 'Bovada', 'spread': -6.0, 'forma...",-6.0
26,401628457,2024,1,regular,2024-08-31T16:00:00.000Z,West Virginia,Big 12,None,Penn State,Big Ten,None,"[{'provider': 'Bovada', 'spread': 10.0, 'forma...",10.0
27,401641015,2024,1,regular,2024-08-31T19:30:00.000Z,UT San Antonio,American Athletic,None,Kennesaw State,Conference USA,None,"[{'provider': 'Bovada', 'spread': -24.0, 'form...",-24.0
28,401644683,2024,1,regular,2024-08-31T19:30:00.000Z,Northwestern,Big Ten,None,Miami (OH),Mid-American,None,"[{'provider': 'Bovada', 'spread': -4.0, 'forma...",-4.0
29,401634304,2024,1,regular,2024-08-31T19:30:00.000Z,Syracuse,ACC,None,Ohio,Mid-American,None,"[{'provider': 'Bovada', 'spread': -17.0, 'form...",-17.0
30,401628455,2024,1,regular,2024-08-31T19:30:00.000Z,Ohio State,Big Ten,None,Akron,Mid-American,None,"[{'provider': 'Bovada', 'spread': -50.0, 'form...",-50.0
31,401629039,2024,1,regular,2024-08-31T19:30:00.000Z,UMass,FBS Independents,None,Eastern Michigan,Mid-American,None,"[{'provider': 'Bovada', 'spread': -2.5, 'forma...",-2.5
32,401634305,2024,1,regular,2024-08-31T16:00:00.000Z,Pittsburgh,ACC,None,Kent State,Mid-American,None,"[{'provider': 'Bovada', 'spread': -24.0, 'form...",-24.0
33,401628461,2024,1,regular,2024-08-31T01:00:00.000Z,Wisconsin,Big Ten,None,Western Michigan,Mid-American,None,"[{'provider': 'Bovada', 'spread': -24.0, 'form...",-24.0
34,401628331,2024,1,regular,2024-08-31T19:30:00.000Z,Texas,SEC,None,Colorado State,Mountain West,None,"[{'provider': 'Bovada', 'spread': -35.0, 'form...",-35.0
35,401643700,2024,1,regular,2024-08-31T20:00:00.000Z,Georgia Southern,Sun Belt,None,Boise State,Mountain West,None,"[{'provider': 'Bovada', 'spread': 11.5, 'forma...",11.5
36,401636608,2024,1,regular,2024-09-01T02:30:00.000Z,Arizona,Big 12,None,New Mexico,Mountain West,None,"[{'provider': 'Bovada', 'spread': -30.0, 'form...",-30.0
37,401628452,2024,1,regular,2024-08-31T23:30:00.000Z,Michigan,Big Ten,None,Fresno State,Mountain West,None,"[{'provider': 'Bovada', 'spread': -21.0, 'form...",-21.0
38,401636611,2024,1,regular,2024-08-31T23:00:00.000Z,Houston,Big 12,None,UNLV,Mountain West,None,"[{'provider': 'Bovada', 'spread': -2.5, 'forma...",-2.5
39,401643701,2024,1,regular,2024-08-31T23:00:00.000Z,Troy,Sun Belt,None,Nevada,Mountain West,None,"[{'provider': 'Bovada', 'spread': -15.5, 'form...",-15.5
40,401636609,2024,1,regular,2024-09-01T02:30:00.000Z,Arizona State,Big 12,None,Wyoming,Mountain West,None,"[{'provider': 'Bovada', 'spread': -6.5, 'forma...",-6.5

In [9]:
stats

,id,season,week,team,opponent,plays_offense,drives_offense,ppa_offense,total_ppa_offense,success_rate_offense,...,passing_downs.success_rate_defense,passing_downs.explosiveness_defense,rushing_plays.ppa_defense,rushing_plays.total_ppa_defense,rushing_plays.success_rate_defense,rushing_plays.explosiveness_defense,passing_plays.ppa_defense,passing_plays.total_ppa_defense,passing_plays.success_rate_defense,passing_plays.explosiveness_defense
0,401403853,2022,1,Hawai'i,Vanderbilt,80,15,-0.196504,-15.720358,0.375000,...,0.380952,2.284470,0.615889,26.483238,0.604651,1.397073,0.047978,1.247420,0.384615,1.771888
1,401403853,2022,1,Vanderbilt,Hawai'i,69,13,0.401894,27.730658,0.521739,...,0.111111,1.539600,-0.363221,-8.717298,0.458333,1.142734,-0.125055,-7.003060,0.339286,1.043512
2,401403854,2022,1,Alabama,Utah State,72,13,0.461649,33.238746,0.541667,...,0.181818,1.597720,-0.202975,-7.510077,0.243243,1.139472,-0.282363,-6.211983,0.181818,1.197334
3,401403854,2022,1,Utah State,Alabama,59,13,-0.232577,-13.722060,0.220339,...,0.529412,2.377240,0.348267,10.796292,0.580645,1.144513,0.547377,22.442454,0.512195,1.653114
4,401403855,2022,1,Arkansas,Cincinnati,70,12,0.229694,16.078613,0.385714,...,0.320000,2.268853,0.155747,4.360914,0.428571,0.983519,0.296841,13.357827,0.400000,1.900264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,401508851,2022,1,South Dakota State,Montana State,50,8,0.598341,29.917065,0.640000,...,0.277778,2.973462,-0.100625,-2.817506,0.357143,0.828034,0.435416,10.885391,0.480000,1.790262
2838,401508870,2022,1,Colorado Mines,Ferris State,53,13,-0.269881,-14.303693,0.339623,...,0.411765,1.560169,0.266709,10.935056,0.512195,0.968332,0.380688,7.233071,0.473684,1.572327
2839,401508870,2022,1,Ferris State,Colorado Mines,60,11,0.302802,18.168127,0.500000,...,0.105263,1.460110,-0.463078,-6.483088,0.285714,0.758980,-0.200528,-7.820605,0.358974,1.116276
2840,401508871,2022,1,Mount Union,North Central,72,10,0.132431,9.535044,0.416667,...,0.181818,2.539994,0.120254,4.689899,0.307692,1.679884,1.026566,10.265664,0.400000,3.459609
2841,401508871,2022,1,North Central,Mount Union,49,11,0.305216,14.955562,0.326531,...,0.375000,2.211902,0.016128,0.516092,0.437500,0.961632,0.225474,9.018951,0.400000,1.376686

In [10]:
games

,id,season,week,home_team,away_team,home_points,away_points,home_division,away_division,home_pregame_elo,away_pregame_elo,neutral_site,point_diff,winner
0,401405059,2022,1,Northwestern,Nebraska,31.0,28.0,fbs,fbs,1361.0,1636.0,True,3.0,Northwestern
1,401405058,2022,1,Illinois,Wyoming,38.0,6.0,fbs,fbs,1496.0,1497.0,False,32.0,Illinois
2,401404146,2022,1,Utah State,Connecticut,31.0,20.0,fbs,fbs,1566.0,1117.0,False,11.0,Utah State
3,401426530,2022,1,Florida Atlantic,Charlotte,43.0,13.0,fbs,fbs,1427.0,1272.0,False,30.0,Florida Atlantic
4,401426531,2022,1,UTEP,North Texas,13.0,31.0,fbs,fbs,1360.0,1426.0,False,-18.0,North Texas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,401437034,2022,14,Boise State,Fresno State,16.0,28.0,fbs,fbs,1750.0,1676.0,False,-12.0,Fresno State
734,401437036,2022,14,Georgia,LSU,50.0,30.0,fbs,fbs,2132.0,1729.0,True,20.0,Georgia
735,401437031,2022,14,Michigan,Purdue,43.0,22.0,fbs,fbs,2144.0,1622.0,True,21.0,Michigan
736,401437009,2022,14,North Carolina,Clemson,10.0,39.0,fbs,fbs,1599.0,1821.0,True,-29.0,Clemson
737,401404145,2022,15,Army,Navy,20.0,17.0,fbs,fbs,1494.0,1462.0,True,3.0,Army

In [11]:
lines

,id,season,week,season_type,start_date,home_team,home_conference,home_score,away_team,away_conference,away_score,lines,consensus_spread(reversed)
0,401411101,2022,1,regular,2022-09-06T00:00:00.000Z,Georgia Tech,ACC,10.0,Clemson,ACC,41.0,"[{'provider': 'consensus', 'spread': 24.5, 'fo...",-24.5
1,401404079,2022,4,regular,2022-09-24T16:00:00.000Z,Kansas,Big 12,35.0,Duke,ACC,27.0,"[{'provider': 'consensus', 'spread': -7.0, 'fo...",7.0
2,401403893,2022,4,regular,2022-09-24T23:00:00.000Z,Texas A&M,SEC,23.0,Arkansas,SEC,21.0,"[{'provider': 'consensus', 'spread': -1.5, 'fo...",1.5
3,401404080,2022,4,regular,2022-09-24T16:00:00.000Z,Iowa State,Big 12,24.0,Baylor,Big 12,31.0,"[{'provider': 'consensus', 'spread': -2.5, 'fo...",2.5
4,401404081,2022,4,regular,2022-09-25T00:00:00.000Z,Oklahoma,Big 12,34.0,Kansas State,Big 12,41.0,"[{'provider': 'consensus', 'spread': -13.5, 'f...",13.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1196,401404090,2022,6,regular,2022-10-08T16:00:00.000Z,Oklahoma,Big 12,0.0,Texas,Big 12,49.0,"[{'provider': 'consensus', 'spread': 7.5, 'for...",-7.5
1197,401404011,2022,6,regular,2022-10-08T19:30:00.000Z,UCLA,Pac-12,42.0,Utah,Pac-12,32.0,"[{'provider': 'consensus', 'spread': 3.0, 'for...",-3.0
1198,401404012,2022,6,regular,2022-10-08T23:30:00.000Z,USC,Pac-12,30.0,Washington State,Pac-12,14.0,"[{'provider': 'consensus', 'spread': -12.5, 'f...",12.5
1199,401404088,2022,6,regular,2022-10-08T23:30:00.000Z,Iowa State,Big 12,9.0,Kansas State,Big 12,10.0,"[{'provider': 'consensus', 'spread': 1.0, 'for...",-1.0
1200,401404089,2022,6,regular,2022-10-08T16:00:00.000Z,Kansas,Big 12,31.0,TCU,Big 12,38.0,"[{'provider': 'consensus', 'spread': 7.0, 'for...",-7.0

In [12]:
df = pd.merge(games, lines[["id", "home_team", "consensus_spread(reversed)"]], on=["id", "home_team"])

In [13]:
df["diff"] = df["point_diff"] - df["consensus_spread(reversed)"]

# If diff is positive, the home team won by more than they should've based on vegas spread.

In [14]:
model_cols = [
    "id",
    "home_team",
    "away_team",
    "home_pregame_elo",
    "away_pregame_elo",
    "neutral_site",
    "consensus_spread(reversed)",
    "diff",
]
df[(df["home_team"]=="Georgia") | (df["away_team"]=="Georgia")][model_cols]

,id,home_team,away_team,home_pregame_elo,away_pregame_elo,neutral_site,consensus_spread(reversed),diff
24,401403858,Georgia,Oregon,1980.0,1574.0,True,16.0,30.0
102,401403888,South Carolina,Georgia,1521.0,2070.0,False,-25.5,-15.5
154,401403895,Georgia,Kent State,2121.0,1274.0,False,45.0,-28.0
257,401403907,Missouri,Georgia,1411.0,2090.0,False,-30.5,26.5
287,401403911,Georgia,Auburn,2058.0,1558.0,False,28.0,4.0
345,401403918,Georgia,Vanderbilt,2087.0,1338.0,False,37.5,17.5
444,401403928,Georgia,Florida,2154.0,1553.0,True,23.0,-1.0
492,401403933,Georgia,Tennessee,2155.0,1970.0,False,10.0,4.0
572,401403944,Mississippi State,Georgia,1688.0,2168.0,False,-16.5,-9.5
620,401403949,Kentucky,Georgia,1583.0,2184.0,False,-22.5,12.5
669,401403959,Georgia,Georgia Tech,2159.0,1245.0,False,36.5,-13.5
719,401437036,Georgia,LSU,2132.0,1729.0,True,17.5,2.5

In [ ]:
# TODO: Previous seasons don't change so store that in a data frame and load it in instead of calling everytime.
# TODO: Load week by week and keep an up-to-date feature store so inference is quick.
# TODO: Keep track of current week in a txt file and write a function to update current week
# TODO: Join features and spreads on games
# TODO: Fit a model using features and store the model
# TODO: Write in a function that reads in the model every time the inference job is run.
# TODO: Write a job that retrains every 'x' weeks.

In [9]:
api_instance = cfbd.StatsApi(cfbd.ApiClient(api_configuration))

stats = api_instance.get_advanced_team_game_stats(year=2023)

In [5]:
test_df = pd.read_csv("/Users/taylorlast/PersonalProjects/cfb-predictions/data/stats_df.csv")
games_df = pd.read_csv("/Users/taylorlast/PersonalProjects/cfb-predictions/data/games_df.csv")

In [6]:
get_latest_feature_values(test_df)

/Users/taylorlast/PersonalProjects/cfb-predictions/src/preprocessing/preprocessing.py:114: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['opponent'], dtype='object')
  stats_df

,team,id,plays_offense,drives_offense,ppa_offense,total_ppa_offense,success_rate_offense,explosiveness_offense,power_success_offense,stuff_rate_offense,...,passing_downs.success_rate_defense,passing_downs.explosiveness_defense,rushing_plays.ppa_defense,rushing_plays.total_ppa_defense,rushing_plays.success_rate_defense,rushing_plays.explosiveness_defense,passing_plays.ppa_defense,passing_plays.total_ppa_defense,passing_plays.success_rate_defense,passing_plays.explosiveness_defense
0,Abilene Christian,401462519,66.142857,12.571429,0.213261,13.497205,0.405540,1.394034,0.621429,0.303604,...,0.324875,2.240784,0.046685,1.786987,0.407978,1.192869,0.317828,11.654470,0.412646,1.614204
1,Air Force,401442040,64.714286,10.000000,0.236201,14.860314,0.455494,1.094662,0.855442,0.089168,...,0.227882,2.252376,0.104683,2.111586,0.391019,0.938435,0.275236,5.032431,0.440902,1.425303
2,Akron,401416652,67.142857,11.857143,0.121093,9.102121,0.440189,1.238823,0.795918,0.160948,...,0.322400,2.177122,0.083174,3.658303,0.427755,0.942706,0.424230,10.658207,0.487214,1.564592
3,Alabama,401442018,69.857143,11.857143,0.305620,21.052245,0.461021,1.359253,0.763946,0.206202,...,0.275606,1.946826,0.192473,6.689322,0.450414,0.976840,0.042169,0.925159,0.370782,1.365572
4,Alabama A&M,401426534,64.571429,11.714286,0.102879,7.316950,0.422710,1.166801,0.789116,0.175212,...,0.344760,2.067794,0.262269,7.610160,0.481103,1.174610,0.167808,6.905666,0.399145,1.634346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,Wisconsin,401442005,63.142857,12.285714,0.130974,7.459375,0.404365,1.265105,0.623129,0.172435,...,0.284143,2.019101,-0.048113,-1.517300,0.318773,0.952957,0.217476,7.109616,0.375685,1.587073
294,Wofford,401413212,54.714286,11.571429,0.258015,11.003969,0.402783,1.512292,0.597506,0.209472,...,0.321882,2.498821,0.303503,8.648024,0.475688,1.136677,0.682233,12.076789,0.517516,2.073094
295,Wyoming,401443543,59.142857,12.285714,0.126860,8.066897,0.400036,1.248483,0.685714,0.178343,...,0.273129,2.064321,0.216196,7.439896,0.472566,0.936315,0.052481,1.891226,0.326374,1.573675
296,Yale,401431402,67.428571,12.285714,0.276471,18.960354,0.458054,1.294414,0.911565,0.103369,...,0.253529,1.991057,0.080648,1.786067,0.406086,1.155106,0.130003,6.290752,0.370169,1.435030
297,Youngstown State,401420827,58.000000,11.571429,0.336766,19.826376,0.496380,1.216958,0.761905,0.095007,...,0.356696,2.038156,0.079185,2.369134,0.390969,0.797354,0.435522,11.792542,0.464879,1.815063

In [13]:
test_df = (
        test_df
        .set_index("id")
        .groupby("team")
        .rolling(7, min_periods=1)
        .mean()
        .groupby("team")
        .shift(1)
        .reset_index()
        .drop(["season", "week", "Unnamed: 0"], axis=1)
)

/var/folders/6y/6p7qrh9s27d1s3l8p2l81vbw0000gn/T/ipykernel_50044/3254997284.py:2: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['opponent'], dtype='object')
  test_df

In [15]:
test_df[test_df["id"] == 400945247]

,team,id,plays_offense,drives_offense,ppa_offense,total_ppa_offense,success_rate_offense,explosiveness_offense,power_success_offense,stuff_rate_offense,...,passing_downs.success_rate_defense,passing_downs.explosiveness_defense,rushing_plays.ppa_defense,rushing_plays.total_ppa_defense,rushing_plays.success_rate_defense,rushing_plays.explosiveness_defense,passing_plays.ppa_defense,passing_plays.total_ppa_defense,passing_plays.success_rate_defense,passing_plays.explosiveness_defense
2,Abilene Christian,400945247,68.500000,14.000000,0.084416,5.096345,0.312956,1.507254,0.250000,0.224856,...,0.376471,1.953956,0.282494,14.709521,0.510691,1.024549,0.564578,8.379752,0.427778,2.186032
7681,New Mexico,400945247,65.571429,11.571429,0.235153,13.794917,0.440560,1.235583,0.784524,0.191140,...,0.408912,1.895525,0.199363,7.971423,0.430624,1.123343,0.480970,12.749474,0.501088,1.606548

In [9]:
# Load configs
api_configs_path = "/Users/taylorlast/PersonalProjects/cfb-predictions/configs/api_configs.yml"
api_configs = load_configs(config_path=api_configs_path)

# Auth API
api_configuration = authenticate_api(api_key=api_configs["API_KEY"])

In [17]:
api_instance =cfbd.BettingApi(cfbd.ApiClient(api_configuration))
spreads = api_instance.get_lines(year=2023)

In [20]:
spreads = api_instance.get_lines(year=2023, week=1)

In [23]:
df = pd.DataFrame().from_records([s.to_dict() for s in spreads])

In [27]:
df[df["home_team"] == "Notre Dame"]["lines"][331]

[{'provider': 'DraftKings',
  'spread': -20.0,
  'formatted_spread': 'Notre Dame -20',
  'spread_open': -20.0,
  'over_under': 50.5,
  'over_under_open': 50.5,
  'home_moneyline': -1350.0,
  'away_moneyline': 800.0},
 {'provider': 'Bovada',
  'spread': -20.5,
  'formatted_spread': 'Notre Dame -20.5',
  'spread_open': -19.5,
  'over_under': 50.5,
  'over_under_open': 49.0,
  'home_moneyline': -1500.0,
  'away_moneyline': 775.0}]

In [124]:
df = pd.read_csv("/Users/taylorlast/PersonalProjects/cfb-predictions/data/current_predictions.csv")

In [125]:
df["diff_in_spread"] = np.abs(df["predicted_diff"])
df.sort_values(by="diff_in_spread", ascending=False)[["home_team", "away_team", "consensus_spread(reversed)", "spread_prediction", "spread"]]

,home_team,away_team,consensus_spread(reversed),spread_prediction,spread
47,Auburn,New Mexico State,25.5,-40.053659,-25.5
52,Kansas,Kansas State,-10.0,-2.448506,10.0
10,Ole Miss,Louisiana Monroe,36.5,-24.942468,-36.5
14,Maryland,Michigan,-18.5,29.469752,18.5
15,Army,Coastal Carolina,-3.0,-7.787675,3.0
...,...,...,...,...,...
26,Wyoming,Hawai'i,13.0,-13.745488,-13.0
2,Bowling Green,Toledo,-10.0,10.317335,10.0
30,Colorado State,Nevada,12.5,-12.213578,-12.5
58,South Carolina,Kentucky,2.0,-2.174956,-2.0
11,Miami,Louisville,1.0,-1.054690,-1.0

In [126]:
df = pd.read_csv("/Users/taylorlast/PersonalProjects/cfb-predictions/data/current_predictions.csv")[["id", "home_team", "away_team", "spread_prediction", "spread"]]

In [127]:
df["delta"] = np.abs(df["spread_prediction"] - df["spread"])

In [128]:
df.sort_values(by="delta", ascending=False).to_csv("juttin.csv")

In [158]:
# Analysis

df = pd.read_csv(r"/Users/taylorlast/PersonalProjects/cfb-predictions/data/running_predictions.csv")

# df = df[~df["home_points"].isna()]

df = df[["id", "inference_date", "spread_prediction", "spread"]]

games_df = pd.read_csv(r"/Users/taylorlast/PersonalProjects/cfb-predictions/data/games_df.csv")
games_df = games_df[["id", "home_team", "away_team", "home_points", "away_points"]]

final_df = pd.merge(df, games_df, on="id")
final_df["diff"] = final_df["away_points"] - final_df["home_points"]

final_df["correct"] = np.where(
    ((final_df["spread_prediction"] > final_df["spread"]) & (final_df["diff"] > final_df["spread"]))
    |
    ((final_df["spread_prediction"] < final_df["spread"]) & (final_df["diff"] < final_df["spread"])),
    True,
    False
)

In [159]:
home_stats = final_df.groupby("home_team").sum()["correct"].sort_values(ascending=False).reset_index().rename(columns={"home_team": "team", "correct": "home_correct"})
away_stats = final_df.groupby("away_team").sum()["correct"].sort_values(ascending=False).reset_index().rename(columns={"away_team": "team", "correct": "away_correct"})

In [160]:
home_stats

                  team  home_correct
0               Kansas             6
1       San José State             6
2           Penn State             6
3              Wyoming             6
4                 Ohio             6
..                 ...           ...
128  Appalachian State             1
129       Oregon State             0
130            Arizona             0
131   Western Michigan             0
132   Western Kentucky             0

[133 rows x 2 columns]

In [161]:
team_correct_df = pd.merge(home_stats, away_stats, on="team")
team_correct_df["correct"] = team_correct_df["home_correct"] + team_correct_df["away_correct"]

In [162]:
team_correct_df.sort_values(by="correct", ascending=False).head(20)

                      team  home_correct  away_correct  correct
40                 Buffalo             4             7       11
1           San José State             6             5       11
10                Illinois             5             5       10
25                Colorado             4             6       10
58                NC State             3             6        9
2               Penn State             6             3        9
108                  UMass             2             7        9
74        Central Michigan             3             6        9
41                     USC             4             5        9
11                   Texas             5             4        9
6                  Liberty             5             3        8
13               Air Force             5             3        8
3                  Wyoming             6             2        8
9                  Indiana             5             3        8
4                     Ohio             6             2        8
42          South Carolina             4             4        8
53                 Hawai'i             3             5        8
31          Michigan State             4             4        8
29              Utah State             4             4        8
23   Florida International             4             4        8

In [163]:
predictions_df = pd.read_csv("/Users/taylorlast/PersonalProjects/cfb-predictions/data/current_predictions.csv")[["id", "home_team", "away_team", "spread_prediction", "spread"]]

In [164]:
this_week = pd.merge(predictions_df, team_correct_df[["team", "correct"]].rename(columns={"correct": "home_correct"}), left_on="home_team", right_on="team").drop("team", axis=1)

this_week = pd.merge(this_week, team_correct_df[["team", "correct"]].rename(columns={"correct": "away_correct"}), left_on="away_team", right_on="team").drop("team", axis=1)

In [165]:
this_week["correct_in_match"] = this_week["home_correct"] + this_week["away_correct"]

In [166]:
this_week["delta"] = np.abs(this_week["spread_prediction"] - this_week["spread"])
this_week.sort_values("correct_in_match", ascending=False).to_csv(r"/Users/taylorlast/PersonalProjects/cfb-predictions/data/taylor.csv")

In [168]:
this_week

,id,home_team,away_team,spread_prediction,spread,home_correct,away_correct,correct_in_match,delta
0,401532450,Western Michigan,Bowling Green,1.024915,3.0,4,6,10,1.975085
1,401532449,Buffalo,Eastern Michigan,-5.688540,-5.5,11,4,15,0.188540
2,401520424,Mississippi State,Ole Miss,13.250524,10.0,4,6,10,3.250524
3,401532452,Akron,Ohio,3.722156,14.0,6,8,14,10.277844
4,401532451,Central Michigan,Toledo,1.762643,9.5,9,7,16,7.737357
...,...,...,...,...,...,...,...,...,...
60,401525904,Kansas State,Iowa State,-5.004939,-10.0,7,6,13,4.995061
61,401532630,Nevada,Wyoming,10.914137,10.0,5,8,13,0.914137
62,401524066,UCLA,California,-13.855714,-9.5,5,7,12,4.355714
63,401532627,San Diego State,Fresno State,8.126404,5.0,7,4,11,3.126404
64,401532626,Hawai'i,Colorado State,-1.818426,5.5,8,7,15,7.318426

In [167]:
this_week[this_week["away_team"]== "Texas"]

Empty DataFrame
Columns: [id, home_team, away_team, spread_prediction, spread, home_correct, away_correct, correct_in_match, delta]
Index: []

In [148]:
team_correct_df[team_correct_df["team"] == "Iowa State"]

    team  home_correct  away_correct  correct
0  Texas             5             2        7

In [108]:
final_df[final_df["home_team"] == "Georgia"]

,id,inference_date,spread_prediction,spread,home_team,away_team,home_points,away_points,diff,correct
54,401520191,2023-09-07 18:30:27.987153,-39.516254,-42.0,Georgia,Ball State,45.0,3.0,-42.0,False
114,401520225,2023-09-16 08:56:41.539929,-25.276062,-27.0,Georgia,South Carolina,24.0,14.0,-10.0,True
202,401520252,2023-09-22 22:47:49.536085,-39.917568,-41.0,Georgia,UAB,49.0,21.0,-28.0,True
309,401520300,2023-10-07 00:17:26.542854,-19.004473,-14.5,Georgia,Kentucky,51.0,13.0,-38.0,True
510,401520364,2023-11-04 11:19:57.752612,-11.448773,-14.5,Georgia,Missouri,30.0,21.0,-9.0,True
594,401520382,2023-11-09 12:28:16.095259,-18.104338,-11.0,Georgia,Ole Miss,52.0,17.0,-35.0,True

In [76]:
df[(df["away_team"] == "Georgia") | (df["home_team"] == "Georgia")]

,inference_date,home_team,away_team,home_points,away_points,spread_prediction,spread,diff,correct
54,2023-09-07 18:30:27.987153,Georgia,Ball State,NaN,NaN,-39.516254,-42.0,NaN,False
114,2023-09-16 08:56:41.539929,Georgia,South Carolina,NaN,NaN,-25.276062,-27.0,NaN,False
202,2023-09-22 22:47:49.536085,Georgia,UAB,NaN,NaN,-39.917568,-41.0,NaN,False
248,2023-09-30 10:49:13.603757,Auburn,Georgia,NaN,NaN,6.308031,14.5,NaN,False
309,2023-10-07 00:17:26.542854,Georgia,Kentucky,NaN,NaN,-19.004473,-14.5,NaN,False
340,2023-10-14 10:40:58.035545,Vanderbilt,Georgia,NaN,NaN,34.314396,32.5,NaN,False
454,2023-10-28 11:38:22.167142,Florida,Georgia,NaN,NaN,23.140600,14.0,NaN,False
510,2023-11-04 11:19:57.752612,Georgia,Missouri,NaN,NaN,-11.448773,-14.5,NaN,False
594,2023-11-09 12:28:16.095259,Georgia,Ole Miss,NaN,NaN,-18.104338,-11.0,NaN,False
648,2023-11-13 15:31:27.059220,Tennessee,Georgia,NaN,NaN,9.543557,10.5,NaN,False
710,2023-11-18 11:06:29.578163,Tennessee,Georgia,NaN,NaN,8.043557,9.0,NaN,False

In [35]:
def ret(paying_users, users):
    revenue = 5 * paying_users
    print(f"revenue: {revenue}")
    twillio_cost = 300 * (1+ users/9000)
    print(f"twillio_cost: {twillio_cost}")
    dev_cost = 2000
    print(f"dev_cost: {dev_cost}")
    data_cost = 1250
    print(f"data_cost: {data_cost}")
    hosting_cost = 100 * (1 + users/10000)
    print(f"hosting_cost: {hosting_cost}")
    cost = twillio_cost + dev_cost + data_cost + hosting_cost
    print(f"cost: {cost}")
    return  revenue - cost

In [49]:
ret(20000, 100000)

revenue: 100000
twillio_cost: 3633.333333333333
dev_cost: 2000
data_cost: 1250
hosting_cost: 1100.0
cost: 7983.333333333333

92016.66666666667

In [157]:
100000 * (1.01)**365

3778343.4332887284